

export const fiveStarResonatorMetadata = {
    "Rover-Havoc": {
        id: 1605,
        qualityLevel: 5,
        imgSrc: "/assets/luckdraw/mrover.webp",
        element: "Havoc",
        portraitSrc: "/assets/portraits/mrover.webp",
    },
    "Rover-Spectro": {
        id: 1502,
        qualityLevel: 5,
        imgSrc: "/assets/luckdraw/frover.webp",
        element: "Spectro",
        portraitSrc: "/assets/portraits/frover.webp",
    },

    Jiyan: {
        id: 1404,
        qualityLevel: 5,
        imgSrc: "/assets/luckdraw/jiyan.webp",
        element: "Broadblade",
        portraitSrc: "/assets/portraits/jiyan.webp",
    },
    Yinlin: {
        id: 1302,
        qualityLevel: 5,
        imgSrc: "/assets/luckdraw/yinlin.webp",
        element: "Electro",
        portraitSrc: "/assets/portraits/yinlin.webp",
    },
    Jinhsi: {
        id: 1304,
        qualityLevel: 5,
        imgSrc: "/assets/luckdraw/jinhsi.webp",
        element: "Spectro",
        portraitSrc: "/assets/portraits/jinhsi.webp",
    },
    Changli: {
        id: 1205,
        qualityLevel: 5,
        imgSrc: "/assets/luckdraw/changli.webp",
        element: "Fusion",
        portraitSrc: "/assets/portraits/changli.webp",
    },
    Zhezhi: {
        id: 1105,
        qualityLevel: 5,
        imgSrc: "/assets/luckdraw/zhezhi.webp",
        element: "Glacio",
        portraitSrc: "/assets/portraits/zhezhi.webp",
    },
    "Xiangli Yao": {
        id: 1305,
        qualityLevel: 5,
        imgSrc: "/assets/luckdraw/xiangli-yao.webp",
        element: "Electro",
        portraitSrc: "/assets/portraits/xiangli-yao.webp",
    },
    Shorekeeper: {
        id: 1505,
        qualityLevel: 5,
        imgSrc: "/assets/luckdraw/shorekeeper.webp",
        element: "Spectro",
        portraitSrc: "/assets/portraits/shorekeeper.webp",
    },
    Camellya: {
        id: 1506,
        qualityLevel: 5,
        imgSrc: "/assets/luckdraw/camellya.webp",
        element: "Havoc",
        portraitSrc: "/assets/portraits/camellya.webp",
    },
    Calcharo: {
        id: 1301,
        qualityLevel: 5,
        imgSrc: "/assets/luckdraw/calcharo.webp",
        element: "Electro",
        portraitSrc: "/assets/portraits/calcharo.webp",
    },
    Verina: {
        id: 1503,
        qualityLevel: 5,
        imgSrc: "/assets/luckdraw/verina.webp",
        element: "Spectro",
        portraitSrc: "/assets/portraits/verina.webp",
    },
    Jianxin: {
        id: 1405,
        qualityLevel: 5,
        imgSrc: "/assets/luckdraw/jianxin.webp",
        element: "Aero",
        portraitSrc: "/assets/portraits/jianxin.webp",
    },
    Lingyang: {
        id: 1104,
        qualityLevel: 5,
        imgSrc: "/assets/luckdraw/lingyang.webp",
        element: "Glacio",
        portraitSrc: "/assets/portraits/lingyang.webp",
    },
    Encore: {
        id: 1203,
        qualityLevel: 5,
        imgSrc: "/assets/luckdraw/encore.webp",
        element: "Fusion",
        portraitSrc: "/assets/portraits/encore.webp",
    },
}